PERIPHERALS = pit
DRIVERS = pacer usb_serial adxl345 panic led nrf24
SRC = hat.c control.c circular_buffer.c communications.c buzzer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
