PERIPHERALS = pit
DRIVERS = pacer usb_serial adxl345 panic led
SRC = control_test.c control.c circular_buffer.c

# Use low level of optimisation to simplify debugging
OPT = -O1

BOARD = hat

include ../../boards/board.mk
